# configuration for A Library Now
# tells the site how to build itself + some site "biographical" info (e.g. title)

title: A Library Now
email: kbd3ax@virginia.edu
description: >- # this means to ignore newlines until "baseurl:"
  Possible exhibit for the Scholars' Lab website, and an
  exploration of what libraries can be in the 21st century.
baseurl: "/library-now" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kbdonnally
github_username: kbdonnally
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
incremental: true
sass:
  sass_dir: assets/css/_sass
  style: expanded # temporary! change back to compressed later
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - docs
  - assets/python
# collections: --> setup for when you add collections
#  people:
#    output: true
#    permalink: /:collection/:name/
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true